services:
  - type: web
    name: roleta-2026
    env: node
    buildCommand: npm install && npx playwright install-deps chromium && npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
